name: Save VRT Cache

on:
  push:
    branches:
      - main

jobs:
  save-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Copy example files
        run: mkdir -p example/.reg && cp -r example/expected example/.reg

      - name: Get commit hash
        id: get-hash
        run: echo "hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Save snapshots cache
        uses: actions/cache/save@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: example/.reg/
          key: reg-${{ steps.get-hash.outputs.hash }}
