name: VRT

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  vrt:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pages: write
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: Setup
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Install example dependencies
        run: cd example && pnpm install --frozen-lockfile

      - name: Get base hash
        id: get-base
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          hash=$(gh api repos/${{ github.repository }}/commits/${{ github.base_ref }} --jq '.sha')
          echo "hash=$hash" >> $GITHUB_OUTPUT

      - name: Restore reg expected
        uses: actions/cache/restore@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: example/.reg/
          key: reg-${{ steps.get-base.outputs.hash }}

      # https://github.com/reg-viz/reg-suit#workaround-for-detached-head
      - name: Workaround for detached HEAD
        run: git checkout ${{github.head_ref}} && git pull

      # Export runtime variables for @actions/artifact
      # https://gist.github.com/LJBNZ/35a59ea05d8d3854b8c31f0495727aed
      - name: Export Actions Runtime Variables
        run: |
          echo "ACTIONS_RESULTS_URL=$ACTIONS_RESULTS_URL" >> $GITHUB_ENV
          echo "ACTIONS_RUNTIME_URL=$ACTIONS_RUNTIME_URL" >> $GITHUB_ENV
          echo "ACTIONS_RUNTIME_TOKEN=$ACTIONS_RUNTIME_TOKEN" >> $GITHUB_ENV

      - name: Run reg-suit
        run: cd example && pnpm reg-suit run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VRT_OUTPUT_DIR: pr/${{ github.event.pull_request.number }}
          REG_NOTIFY_CLIENT_ID: ${{ secrets.REG_NOTIFY_CLIENT_ID }}
