name: VRT

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  vrt:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pages: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Install example dependencies
        run: cd example && pnpm install --frozen-lockfile

      - name: Get base hash
        id: get-base
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          hash=$(gh api repos/${{ github.repository }}/commits/${{ github.base_ref }} --jq '.sha')
          echo "hash=$hash" >> $GITHUB_OUTPUT

      - name: Restore reg expected
        uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: example/.reg/
          key: reg-${{ steps.get-base.outputs.hash }}

      # https://github.com/reg-viz/reg-suit#workaround-for-detached-head
      - name: Workaround for detached HEAD
        run: git checkout ${{github.head_ref}} && git pull

      - name: Run reg-suit
        run: cd example && pnpm reg-suit run
        env:
          VRT_OUTPUT_DIR: pr/${{ github.event.pull_request.number }}
          REG_NOTIFY_CLIENT_ID: ${{ secrets.REG_NOTIFY_CLIENT_ID }}

      # The following deployment steps are required when GitHub Pages
      # "Build and deployment" Source is set to "GitHub Actions"
      - name: Checkout gh-pages
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: gh-pages
          path: gh-pages-dir

      - name: Upload pages artifact
        id: upload
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: gh-pages-dir

      # Deploy to GitHub Pages similar to actions/deploy-pages
      - name: Deploy to GitHub Pages
        uses: ./.github/actions/deploy-pages
        with:
          artifact_id: ${{ steps.upload.outputs.artifact_id }}
